version: '2.2'
services:
  arangodb:
    image: arangodb/arangodb:3.8.1
    restart: unless-stopped
    environment:
      ARANGO_ROOT_PASSWORD: M1qLriWYtac2KQgRIf15xDenrwjqxfpa
    volumes:
      - arangodb:/var/lib/arangodb3
    ulimits:
      nofile:
        hard: 1048576
        soft: 1048576
    networks: [ catalyst ]

  emitter:
    image: emitter/server
    restart: unless-stopped
    environment:
      - EMITTER_LICENSE=PfA8ID8izeSlDUlNZgNXo77DQV9QzlNtxTk64WreCXKfDZsREAVXUXwh20UKOZdkALbLTmOytO_iC6mc_twKAQ:3
    networks: [ catalyst ]

  minio:
    image: minio/minio:RELEASE.2021-12-10T23-03-39Z
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - minio:/data
    command: server /data
    networks: [ catalyst ]

  postgres:
    image: postgres:13
    restart: unless-stopped
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks: [ catalyst ]

  keycloak:
    image: quay.io/keycloak/keycloak:14.0.0
    restart: unless-stopped
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: RV3AOsWZ12C6CGOvelmZe9Wt0fN09qN6
      KEYCLOAK_IMPORT: /tmp/realm.json
      PROXY_ADDRESS_FORWARDING: "true"
      # KEYCLOAK_FRONTEND_URL: http://localhost:9002
    volumes:
      - ./realm.json:/tmp/realm.json
    depends_on: [ postgres ]
    networks: [ catalyst ]

  catalyst:
    image: ghcr.io/securitybrewery/catalyst:main
    restart: unless-stopped
    environment:
      SECRET: 4ef5b29539b70233dd40c02a1799d25079595565e05a193b09da2c3e60ada1cd
      EXTERNAL_ADDRESS: http://localhost
      OIDC_ISSUER: http://localhost:9002/auth/realms/catalyst
      OIDC_CLIENT_SECRET: d3ec0d91-b6ea-482d-8a4e-2f5a7ca0b4cb
      ARANGO_DB_HOST: http://arangodb:8529
      ARANGO_DB_PASSWORD: M1qLriWYtac2KQgRIf15xDenrwjqxfpa
      S3_PASSWORD: minio123
      EMITTER_IO_KEY: A9RysEsPJni8RaHeg_K0FKXQNfBrUyw-
      AUTH_BLOCK_NEW: "false"
      INITIAL_API_KEY: d0169af94c40981eb4452a42fae536b6caa9be3a
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on: [ arangodb, emitter, minio, keycloak ]
    extra_hosts:
      - "localhost:172.17.0.1"
    networks: [ catalyst ]

volumes:
  minio:
  postgres_data:
  arangodb:

networks:
  catalyst:
    name: catalyst
